export const FETCH_ALL_CUSTOMERS = 'FETCH_ALL_CUSTOMERS';
export const FETCH_ONE_CUSTOMER = 'FETCH_ONE_CUSTOMER';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const SELECT_CUSTOMER = 'SELECT_CUSTOMER';
export const ACTION_ERROR = 'ACTION_ERROR';
